version: 2
updates:
  # Goモジュールの依存関係のアップデートを監視
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - yuorei

  # Dockerイメージの依存関係のアップデートを監視
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - yuorei

  # GitHub Actionsワークフローの依存関係のアップデートを監視
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - yuorei
