apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-server
  template:
    metadata:
      labels:
        app: video-server
    spec:
      containers:
      - name: video-server
        image: yuorei/video-server:1644e744bf9945aff7ac9a9c03601a04790892fd
        ports:
        - containerPort: 8080
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: aws_access_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: aws_secret_access_key
          - name: PORT
            value: "8080"
          - name: AWS_S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: aws_endpoint_url
          - name: AWS_S3_URL
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: aws_s3_url
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: mongodb_uri
          - name: AUTH_URL
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: auth_url

