apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-server
  template:
    metadata:
      labels:
        app: video-server
    spec:
      containers:
      - name: video-server
        image: yuorei/video-server:5332315e738f9844e38cc0b3e9231b750b496dc3
        ports:
        - containerPort: 8080
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: aws_access_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: aws_secret_access_key
          - name: PORT
            value: "8080"
          - name: AWS_ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: aws_endpoint_url
          - name: IMAGE_URL
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: image_url
          - name: CORS_URL
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: cors_url
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: mongo_initdb_root_username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: mongo_initdb_root_password
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: mongodb_uri

