apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-server
  template:
    metadata:
      labels:
        app: video-server
    spec:
      containers:
      - name: video-server
        image: yuorei/video-server:08af786d1a40b60b26d18fe7f5b10a458c6c7ea2
        ports:
        - containerPort: 8080
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: aws_access_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: video-secret
                key: aws_secret_access_key
          - name: PORT
            value: "8080"

